### ISSUE TITLE
Bug: Error When Running "find" device

### ISSUE THREAD

**Issue by blissdev** [sopelj/python-ember-mug#66]
### Unexpected behaviour

I tried to run `ember-mug find` but was presented with an error.	

### Expected behaviour

Found a device? I'm not sure what the output is supposed to look like.

### Steps to reproduce

- Run `ember-mug find`

### Python Version

3.8.15

### Operating System

macOS

### Errors/Logs

```shell
Traceback (most recent call last):
  File "/usr/local/bin/ember-mug", line 8, in <module>
    sys.exit(run_cli())
  File "/Library/Python/3.9/site-packages/ember_mug/cli/__init__.py", line 13, in run_cli
    asyncio.run(cli.run())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Library/Python/3.9/site-packages/ember_mug/cli/commands.py", line 232, in run
    await self._commands[args.command](args)
  File "/Library/Python/3.9/site-packages/ember_mug/cli/commands.py", line 40, in find_device
    device = await find_mug(mac=args.mac, adapter=args.adapter)
AttributeError: 'Namespace' object has no attribute 'adapter'
```

**Comment by blissdev** [comment]
After upgrading to python 3.13 I was able to run `find` without error.

**Comment by sopelj** [comment]
> After upgrading to python 3.13 I was able to run `find` without error.

Oh I'm glad it's working for you on 3.13. I have only specifically tested it on 3.10, 3.11 and 3.12.  

I'll see if 3.13 is fully supported by the underlying libraries and if so I'll add support officially too this week.
